# Default values for harvester-vm-dhcp-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rancher/harvester-vm-dhcp-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main-head"

# Agent configuration (defaults for dynamically created agents)
agent:
  replicaCount: 1 # Each dynamic agent deployment will likely have 1 replica
  image:
    repository: rancher/harvester-vm-dhcp-agent # Specific agent image
    pullPolicy: IfNotPresent
    tag: "main-head" # Or specific version for agent
  # Flag to disable leader election within the agent pods
  # Note: Each dynamic agent instance will perform its own leader election if not disabled.
  # Consider if leader election is needed per-agent-instance or if a different HA model is desired.
  # For now, keeping this, assuming each agent instance (per IPPool) might need it if it were replicated.
  noLeaderElection: false
  # serviceAccount.create, .name and rbac.create are no longer used for a single static agent.
  # The controller creates SAs and CRBs for each dynamic agent.
  # Annotations for dynamically created SAs could be added here if needed.
  serviceAccount:
    annotations: {}
  # Pod security context for agent pods
  podSecurityContext: {}
  # Security context for agent containers
  securityContext: {}
  # Resources requests and limits for agent pods
  resources: {}
  # Node selector, affinity, tolerations for agent pods
  nodeSelector: {}
  affinity: {}
  tolerations: []

webhook:
  replicaCount: 1
  image:
    repository: rancher/harvester-vm-dhcp-webhook
    pullPolicy: IfNotPresent
    tag: "main-head"
  httpsPort: 8443
  service:
    type: ClusterIP
    port: 443
  resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  metricsPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
