{{- if .Values.agent.enabled -}}
{{- if .Values.agent.rbac.create -}}
apiVersion: {{ template "harvester-vm-dhcp-controller.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "harvester-vm-dhcp-controller.fullname" . }}-agent
  labels:
    {{- /* Rimuovi l'helper labels per evitare duplicati e definisci direttamente */}}
    helm.sh/chart: {{ include "harvester-vm-dhcp-controller.chart" . }}
    app.kubernetes.io/name: {{ include "harvester-vm-dhcp-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: agent # Etichetta corretta
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # Core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""] # Core API group
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["network.harvesterhci.io"]
  resources: ["ippools"]
  verbs: ["get", "list", "watch"]
{{- end -}}
{{- end -}}
