apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
rules:
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "watch", "list", "update", "patch", "create" ]
- apiGroups: [ "network.harvesterhci.io" ]
  resources: [ "ippools", "ippools/status", "virtualmachinenetworkconfigs", "virtualmachinenetworkconfigs/status" ]
  verbs: [ "*" ]
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources: [ "network-attachment-definitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "watch", "list" ]
- apiGroups: [ "kubevirt.io" ]
  resources: [ "virtualmachines" ]
  verbs: [ "get", "watch", "list" ]
---
# This is the new shared ClusterRole for all dynamically created DHCP agents
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name needs to be consistent and known by the main controller (e.g., via env var)
  # Let's use a name based on Release.Name for now.
  # This was previously {{ .Release.Name }}-dhcp-agent-clusterrole
  # Let's rename to {{ .Release.Name }}-vm-dhcp-agent-shared-permissions
  name: {{ .Release.Name }}-vm-dhcp-agent-shared-permissions
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"] # For leader election
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"] # For leader election if not using leases
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["network.harvesterhci.io"]
  resources: ["ippools"] # To get its IPPool config (the one specified in IPPOOL_REF)
  verbs: ["get", "watch", "list"] # Needs get for specific IPPool, list/watch for its cache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
rules:
- apiGroups: [ "admissionregistration.k8s.io" ]
  resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
  verbs: [ "list", "update", "create" ]
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "apiregistration.k8s.io" ]
  resources: [ "apiservices" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "network.harvesterhci.io" ]
  resources: [ "ippools", "virtualmachinenetworkconfigs" ]
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "watch", "list", "create", "update", "patch" ]
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources: [ "network-attachment-definitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "kubevirt.io" ]
  resources: [ "virtualmachines" ]
  verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# Removed static agent ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: {{ include "harvester-vm-dhcp-controller.name" . }}-agent
#   labels:
#   {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: {{ include "harvester-vm-dhcp-controller.name" . }}-agent # This role was also removed and replaced by the shared one
# subjects:
# - kind: ServiceAccount
#   name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-agent # Static agent SA, no longer created by default
#   namespace: {{ .Release.Namespace }}
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-webhook
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-deployment-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
- apiGroups: [""] # Core API group
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # New ClusterRole to manage ClusterRoleBindings
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-crb-manager
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # Bind the new ClusterRole to the controller's SA
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-crbs
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-crb-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-agent-deployments
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }} # Controller's SA
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-deployment-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-lease-manager
  namespace: kube-system
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "watch", "list", "update", "create" ]
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "leases" ]
  verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-pod-manager
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "create", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-secret-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-leases
  namespace: kube-system
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-lease-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-pods
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-pod-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-manage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-secret-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-webhook
  namespace: {{ .Release.Namespace }}

